@baseUrl = http://localhost:5264

### 
POST {{baseUrl}}/Auth/register
Content-Type: application/json

{
  "username": "jdoe",
  "password": "P@ssw0rd123",
  "name": "John Doe",
  "licenseNumber": "TR-12345"
}

###

### 
# @name login
POST {{baseUrl}}/Auth/login
Content-Type: application/json

{
  "username": "jdoe",
  "password": "P@ssw0rd123"
}

###

### 
POST {{baseUrl}}/Flights
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "originICAO": "LTFM",
  "destinationICAO": "EGLL",
  "flightTime": "03:45:00",
  "aircraftType": "A320",
  "date": "2026-07-16",
  "metarInfo": null
}

###

### 
GET {{baseUrl}}/Flights
Accept: application/json